name: Build
on:
  push:
    branches: [main]
    paths:
    - '**.cs'
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup .Net
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: Build
        run: dotnet build
